name: Pinact
on:
  pull_request:
    branches:
    - master
permissions:
  contents: read
jobs:
  pinact:
    uses: hsn723/actions/.github/workflows/pinact.yml@a48f27c3e6fa5b0a099473cd4ff0aa71dafb6569 # v1.0.40
