name: Pinact
on:
  pull_request:
    branches:
    - master
permissions:
  contents: read
jobs:
  pinact:
    uses: hsn723/actions/.github/workflows/pinact.yml@d7fb9a279f99f27dfd9aa008a97c6ec92ccfa330 # v1.0.34
